### ISSUE TITLE
Inconsistent naming of image_cols and label_cols

### ISSUE THREAD

**Issue by markus-hinsche** [kbressem/trainlib#1]
`config_template.yaml` defines
```
  image_cols: [image_1, image_2]
  label_cols: label
```

where `test_config.yaml` defines:
```
  image_cols: image
  label_cols: label
```

Also the naming is inconsistent:
* A list should have plural ending (e.g. `cols`) while a string could have a non-plural name e.g. `col`

**Comment by kbressem** [comment]
In `config_template.yaml` it's an example how two images, e.g. T2w and T1w sequence could be loaded. These two sequences will go through all transforms together and will then be concatenated to the channel dim before passed to the model. 

In `test_config.yaml` it's just a single image. 

`label_cols` also supports a list or single name.

**Comment by markus-hinsche** [comment]
Yes but debughandler then doesn‘t support not -lists

Keno ***@***.***> schrieb am Fr. 9. Sept. 2022 um 23:25:

**Comment by kbressem** [comment]
`DebugHandler`does not interact with `image_cols` or `label_cols`. Instead it displays statistics for the batch, before it is passed to the model. For this it interacts with the `dict` created in MONAI dict transforms. 
`trainlib` always combined all images from `image_cols` to a single instance with the key `image` (or [`monai.utils.enums.CommonKeys.IMAGE`](https://docs.monai.io/en/stable/utils.html#monai.utils.enums.CommonKeys)) and all instances from `label_col` to `label`. This is then accessed by `DebugHandler`.

**Comment by markus-hinsche** [comment]
When I put the config
```
 image_cols: image
  label_cols: label
```
into DebugHandler, I get:

```
KeyError: 'i'
```

Here is the full error
https://gist.github.com/markus-hinsche/6fa406adf0d236ebd8862e4bcdaff3b7

This is (I think) because I is the first letter of "image" string, instead of the first element in a list it chose the first letter of a string

But maybe it's supposed to be used differently with a modified config. Maybe this is just not intuitive to me

**Comment by markus-hinsche** [comment]
This is just a suggestion how to improve trainlib so it would be more intuitive to other people

**Comment by kbressem** [comment]
`load_config` automatically converts the string to a list of `len==1`. 
Does the column `image` exist in your csv?

**Comment by kbressem** [comment]
Has been resolved in https://github.com/rAIdiance/chest/pull/9
