### ISSUE TITLE
Relative imports vs. absolute imports

### ISSUE THREAD

**Issue by markus-hinsche** [kbressem/trainlib#12]
Just an idea: Why not use absolute imports

> Generally, Python developers prefer absolute import when they are working on shared or big projects.
([src](https://www.techgeekbuzz.com/blog/absolute-vs-relative-imports-in-python/))

https://github.com/Project-MONAI/MONAI uses absolute imports

**Comment by kbressem** [comment]
Sounds good. But I do not completely understand it yet. Can you elaborate, maybe provide an example, where a relative import is used and how it would change to an absolute import?

**Comment by markus-hinsche** [comment]
Consider `trainer.py` as an example

Currently imports are like this:
```
from . import loss, model, optimizer
from .data import segmentation_dataloaders
from .handlers import DebugHandler, PushnotificationHandler
from .transforms import get_post_transforms
from .utils import USE_AMP, import_patched
```

I want us to consider the alternative:
```
from trainlib import loss
from trainlib import model
from trainlib import optimizer
from trainlib.data import segmentation_dataloaders
from trainlib.handlers import DebugHandler, PushnotificationHandler
from trainlib.transforms import get_post_transforms
from trainlib.utils import USE_AMP, import_patched
```

Apart from trainer.py, we would also change all other modules with imports of the own code inside trainlib.

Both relative and absolute have pros and cons (see linked article above)

According to many best practices, medium-size or bigger projects prefer absolute imports. 

Not a big issue though, was just a thought

**Comment by kbressem** [comment]
#32
