### ISSUE TITLE
SpatialPadd's mode 

### ISSUE THREAD

**Issue by markus-hinsche** [kbressem/trainlib#16]
`SpatialPadd`'s mode has a completely different meaning from `mode: [bilinear, nearest]` but it is still added to the transform by `transforms.mode` key.
https://docs.monai.io/en/stable/transforms.html#monai.transforms.SpatialPadd

> "constant", "edge", "linear_ramp", "maximum", "mean", "median", "minimum", "reflect", "symmetric", "wrap", "empty"} available modes for

To avoid confusion, we should consider removing the overall `transforms.mode` and have each config define a mode if needed

**Comment by kbressem** [comment]
You can overwrite the `mode` argument for all transforms. Still, it makes sense to remove a global default for mode. Feel free to do so
