### ISSUE TITLE
`data` module naming

### ISSUE THREAD

**Issue by markus-hinsche** [kbressem/trainlib#21]
I suggest renaming `data.py` to something more distinct, e.g. `data_loaders.py`: [data.py](https://github.com/kbressem/trainlib/blob/main/trainlib/data.py)

Reasoning: 
- https://github.com/kbressem/trainlib/tree/main/data This dir has the same name
- `monai.data` package has the same name

To avoid confusion, I would suggest to find another name

**Comment by kbressem** [comment]
I understand your reasoning, but I am also not happy with `data_loaders.py`, given that `data.py` does more than building DataLoaders, like building datasets and adapting paths. The reason I named it `data` was to keep it consistent with `monai.data`.
