### ISSUE TITLE
Custom DataLoader.show_batch only works for 3D

### ISSUE THREAD

**Issue by markus-hinsche** [kbressem/trainlib#23]
Task: Make this work for 2D as well

**Comment by kbressem** [comment]
Can you go into more details, what you would like to have in a 2D viewer? Should it be the same as the 3D or have different features. 

Furthermore, I believe the viewer also does not support multiple inputs. So thats also a feature we would need to add

**Comment by markus-hinsche** [comment]
I haven't explored or tried what the 3D viewer provides

The 2D viewer prototype I have is able to show 
- multiple samples (one per row)
- the x-ray (first column)
- different segmentations overlayed (2nd column)
- x-ray + segmentations all overlayed (3rd column)
- ideally different segmentation strength show, e.g. by lighter or darker color
- ideally different segmentation types (lung vs. heart) show, e.g. by using different colors
- maybe there is the option to show different segmentation types (lung vs. heart) in multiple columns, 1 segm type per column

screenshot
![image](https://user-images.githubusercontent.com/1809832/193249438-954c2c0d-de27-4a8a-b9a5-499b8ca010c6.png)

**Comment by kbressem** [comment]
I think 2D can integrated easy into the current viewer (as it only shows 2D slices).  

However, labels with overlap would require a rewrite as I have not considered it when writing the viewer (and it's very rare for 3D)

**Comment by markus-hinsche** [comment]
We discussed to provide basic 2D viewing functionality here, but overlap or other project-specific requirements are handled in the more specific repos

**Comment by kbressem** [comment]
Let's first make a quick implementation for basic 2D, to get you going in the chest project. Than maybe later some advanced viewing features.
