### ISSUE TITLE
SegmentationTrainer metrics vs handlers

### ISSUE THREAD

**Issue by markus-hinsche** [kbressem/trainlib#39]
SegmentationTrainer gets a metrics arg, but the parameter elements are then looked up in [handers](https://docs.monai.io/en/stable/handlers.html#mean-squared-error-metrics-handler).

Would it be more intuitive to name the parameter `handlers`?

**Comment by kbressem** [comment]
I don't think this would be a good idea, as there are multiple other handlers (e.g. the DebugHandler, StatsHandler, TensorBoardHandler, etc. ) that could not be added with this argument. 

With `metrics` you only can attach metric handlers.
