### ISSUE TITLE
🔀 Restructure Trainer (support classification)

### ISSUE THREAD

**Issue by kbressem** [kbressem/trainlib#41]
Currently, `trainlib` only supports segmentation, but classification should also be possible. 
Therefore, the trainer needs to be restructured. Probably the best way is a baseclass (`BaseTrainer`) and task-specific sub classes (`SegmentationTrainer`, `ClassificationTrainer`)

**Comment by markus-hinsche** [comment]
@kbressem Any progress on the classification trainer? Does it make sense I support this? Otherwise, I have to write custom trainlib-independent code in order to progress in the deepspa project

**Comment by kbressem** [comment]
Feel free to use custom code on the project
